### ISSUE TITLE
程序报错求解答

### ISSUE THREAD

**Issue by pwy1327347084** [GuoQuanhao/YOLOv5-Paddle#20]
大佬您好，我从百度飞桨AI studio来的，我之前使用您复现的yolov5-paddle时，一直没问题，今天使用时报错了。一个是ConnectionRefusedError: [Errno 111] Connection refused；另一个是urllib.error.URLError: <urlopen error [Errno 111] Connection refused>。这个要怎么解决呢

**Comment by LyonWu21** [comment]
同问

**Comment by 13950182204** [comment]
同问
这个文件下载不了啊ttf这个http://182.61.54.236/yolov5/Arial.ttf

**Comment by 13950182204** [comment]
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 641, in <module>
    main(opt)
  File "train.py", line 530, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 113, in train
    data_dict = data_dict or check_dataset(data)  # check if None
  File "/home/aistudio/yolov5-Paddle-main/utils/general.py", line 564, in check_dataset
    check_font('Arial.ttf' if is_ascii(data['names']) else 'Arial.Unicode.ttf', progress=True)  # download fonts
  File "/home/aistudio/yolov5-Paddle-main/utils/general.py", line 499, in check_font
    download_url_to_file(url, str(file), progress=progress)
  File "/home/aistudio/yolov5-Paddle-main/utils/downloads.py", line 57, in download_url_to_file
    u = urlopen(req)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/urllib/request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
